services:
  otel-collector:
      image: otel/opentelemetry-collector:latest
      command: [ "--config=/etc/otel-collector-config.yml" ]
      volumes:
        - ./otel-collector-config.yml:/etc/otel-collector-config.yml
      ports:
        - "4317:4317"  
        - "55681:55681" 
      depends_on:
        - zipkin
        
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
    restart: always

  service-a:
    build:
      context: ./service-a/
      dockerfile: Dockerfile
    container_name: service-a
    ports:
      - "8080:8080"
    environment:
      - OTEL_SERVICE_NAME=servico-a
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SERVICE_B_URL=http://service-b:8081/cep
    depends_on:
      - zipkin
    restart: always

  service-b:
    build:
      context: ./service-b/
      dockerfile: Dockerfile
    container_name: service-b
    env_file:
      - ./service-b/.env
    volumes:
      - ./.env:/app/.env
    ports:
      - "8081:8081"
    environment:
      - OTEL_SERVICE_NAME=servico-b
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
    restart: always
